### ISSUE TITLE
No logs in my deployment

### ISSUE THREAD

**Issue by saffronjam** [kthcloud/landing-frontend#117]
I don't get any logs in the frontend for my deployment, but from Postman it's fine.

Frontend:
![image](https://github.com/kthcloud/landing-frontend/assets/26722370/8b33ef85-c4f6-481b-884c-ea177a66567b)

Postman (same request):
![image](https://github.com/kthcloud/landing-frontend/assets/26722370/2b76aa69-54f7-42fb-947b-a558fc6532a2)

**Comment by pierrelefevre** [comment]
Fixed in #119
